Repository AerynOS/recipes, pull requests merged in 2024-08, with the labels that each got.

#228 Update ncurses to 6.5 & screen to 4.9.1
  n/ncurses/manifest.x86_64.bin
  n/ncurses/manifest.x86_64.jsonc
  n/ncurses/stone.yaml
  s/screen/manifest.x86_64.bin
  s/screen/manifest.x86_64.jsonc
  s/screen/stone.yaml
  t/tomoyo-tools/manifest.x86_64.bin
  t/tomoyo-tools/manifest.x86_64.jsonc
  t/tomoyo-tools/pkg/use_serpent_ncurses_location.patch
  t/tomoyo-tools/stone.yaml
Labels: security

#241 Exiv2 0.28.3
  e/exiv2/manifest.x86_64.bin
  e/exiv2/manifest.x86_64.jsonc
  e/exiv2/stone.yaml
Labels: security

#242 expat: Update to 2.6.2
  e/expat/manifest.x86_64.bin
  e/expat/manifest.x86_64.jsonc
  e/expat/stone.yaml
Labels: security

#243 libarchive: Update to 3.7.4
  l/libarchive/manifest.x86_64.bin
  l/libarchive/manifest.x86_64.jsonc
  l/libarchive/stone.yaml
Labels: security

#230 tools: Add prepare-commit-msg hook
  justfile
  tools/prepare-commit-msg.py
Labels: type: enhancement, area: tooling

#247 dmidecode: Add at 3.6
  d/dmidecode/manifest.x86_64.bin
  d/dmidecode/manifest.x86_64.jsonc
  d/dmidecode/stone.yaml
Labels: type: enhancement, area: package

#274 lmdb: Autogenerate correct lmdb.pc on each build
  l/lmdb/manifest.x86_64.bin
  l/lmdb/manifest.x86_64.jsonc
  l/lmdb/pkg/generate-lmdb.pc.sh
  l/lmdb/pkg/lmdb.pc.in
  l/lmdb/stone.yaml
Labels: type: bug, area: package

#283 Flatpak 1.14.10
  b/bubblewrap/manifest.x86_64.bin
  b/bubblewrap/manifest.x86_64.jsonc
  b/bubblewrap/stone.yaml
  f/flatpak/manifest.x86_64.bin
  f/flatpak/manifest.x86_64.jsonc
  f/flatpak/stone.yaml
Labels: security

#306 Networking updates
  i/iproute2/manifest.x86_64.bin
  i/iproute2/manifest.x86_64.jsonc
  i/iproute2/pkg/stateless/serpent.patch
  i/iproute2/stone.yaml
  l/libmicrohttpd/manifest.x86_64.bin
  l/libmicrohttpd/manifest.x86_64.jsonc
  l/libmicrohttpd/stone.yaml
  l/libndp/manifest.x86_64.bin
  l/libndp/manifest.x86_64.jsonc
  l/libndp/stone.yaml
  l/libnftnl/manifest.x86_64.bin
  l/libnftnl/manifest.x86_64.jsonc
  l/libnftnl/stone.yaml
  l/libnl/manifest.x86_64.bin
  l/libnl/manifest.x86_64.jsonc
  l/libnl/stone.yaml
  n/networkmanager/manifest.x86_64.bin
  n/networkmanager/manifest.x86_64.jsonc
  n/networkmanager/stone.yaml
  n/nftables/manifest.x86_64.bin
  n/nftables/manifest.x86_64.jsonc
  n/nftables/stone.yaml
  n/nghttp2/manifest.x86_64.bin
  n/nghttp2/manifest.x86_64.jsonc
  n/nghttp2/stone.yaml
  n/nss/manifest.x86_64.bin
  n/nss/manifest.x86_64.jsonc
  n/nss/stone.yaml
  p/ppp/manifest.x86_64.bin
  p/ppp/manifest.x86_64.jsonc
  p/ppp/pkg/stateless.patch
  p/ppp/stone.yaml
  w/wget/manifest.x86_64.bin
  w/wget/manifest.x86_64.jsonc
  w/wget/pkg/0001-libwget-openssl-Use-vendor-SSL-certs-for-now.patch
  w/wget/stone.yaml
Labels: security

#322 libuv: Update to 1.48.0
  l/libuv/manifest.x86_64.bin
  l/libuv/manifest.x86_64.jsonc
  l/libuv/stone.yaml
Labels: security

#244 libxml2: Update to 2.13.3
  l/libxml2/manifest.x86_64.bin
  l/libxml2/manifest.x86_64.jsonc
  l/libxml2/stone.yaml
Labels: security
